spring.application.name=WorkFlowProject
server.port=8086

# ==========================================
# Mailtrap Canlı SMTP Konfigürasyonu
# ==========================================
spring.mail.host=live.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=api
spring.mail.password=19082e45ea1d1ae973deb4d4c3991f68

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ==========================================
# Deep Link İçin Frontend URL Adresi
# ==========================================
app.frontend-url=http://localhost:3000

app.backend-url=http://localhost:8086

spring.security.user.name=admin
spring.security.user.password=123